### ISSUE TITLE
Bug: Multiple principals in an IAM policy are flagged as errors

### ISSUE THREAD

**Issue by BrutalSimplicity** [threadheap/serverless-ide-vscode#101]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* **What is the current behavior?**
 In Serverless IAM policies it currently flags multiple AWS principals as an error.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar.

```
service:
  name: some-api

provider:
  name: aws
  runtime: python3.8
  resourcePolicy:
    - Effect: Allow
      Action:
        - execute-api:Invoke
      Principal:
        AWS:
          - "arn:aws:iam::*:role/swa/one-role"
          - "arn:aws:iam::*:role/swa/two-role"
      Resource:
        - arn:aws:execute-api:us-east-1:*:*/${opt:stage}/*/path/to/resource
```

* **What is the expected behavior?**

It should support an array or string for the `Principal` field.

* **Please tell us about your environment:**
  
  - Plugin version: 0.5.24
  - VSCode version: 1.47.1
  - Template type: Serverless
