### ISSUE TITLE
Bug: SSE for Deployment Bucket should allow aws:kms

### ISSUE THREAD

**Issue by BrutalSimplicity** [threadheap/serverless-ide-vscode#104]
Given the following serverless definition:

```
service: service-name

provider:
  name: aws
  stackName: stack-name
  deploymentBucket:
    name: existing-deployment-bucket
    serverSideEncryption: aws:kms
    sseKMSKeyId: some-kms-key-arn
```

The Serverless IDE flags `aws:kms` as an invalid parameter. The valid parameters for that definition are `['aws:kms', 'AES256']`.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.
