### ISSUE TITLE
Value is not accepted. Valid values: ... in httpApi code block

### ISSUE THREAD

**Issue by medmemara** [threadheap/serverless-ide-vscode#107]
The Serverless IDE is reporting an error when using the httpApi Event method type for a lambda function.

[Serverless IDE] Value is not accepted. Valid values: "get", "head", "patch", "post", "put", "delete", "options", "trace", "connect", **"any"**, "GET", "HEAD", "PATCH", "POST", "PUT", "DELETE", "OPTIONS", "TRACE", "CONNECT".

VSCode Version: 1.49.0
Serverless IDE Version: 0.5.26

I have a serverless yml similar to the following:
```yaml
service:
  name: example-service

provider:
  name: aws
  runtime: nodejs12.x

functions:
  main:
    handler: handler.handler
    events:
      - httpApi:
          method: '*' # Error [Serverless IDE] Value is not accepted
          # method: 'any' # passed validation. but sls package failed.
  main2:
    handler: handler.handler2
    events:
      - http:
         method: 'any' # passed validation & sls package

```
