### ISSUE TITLE
Type property of authorizer has wrong valid values

### ISSUE THREAD

**Issue by FerroO2000** [threadheap/serverless-ide-vscode#108]
An error when using the authorizerId prop to refer a custom authorizer.

```yml
functions:
  func1:
    ...
    events:
      - http:
          ...
          authorizer:
            authorizerId: !Ref ApiGatewayAuthorizer
            type: CUSTOM #[Serverless IDE] Value is not accepted. Valid values: "token", "request", "cognito_user_pools".

```

The correct values for the type prop, when authorizerId is present, are:
ONE, AWS_IAM, CUSTOM, COGNITO_USER_POOLS, AWS_CROSS_ACCOUNT_IAM, JWT
