### ISSUE TITLE
Serverless Framework - layers schema incorrectly flags 'package' and 'path' properties when used together

### ISSUE THREAD

**Issue by baybars1223** [threadheap/serverless-ide-vscode#129]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
  * Layers with both `path` and `package` are incorrectly red-flagged as 'Matches multiple schemas when only one must validate'
  * `layer.package.include` is red-flagged as 'Incorrect type. Expected "string".'

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 
  * Add a layer
  * Add `path` property (necessary because you're not packaging an artifact)
  * Add `package` property with `include` or `exclude` properties but not `artifact`
![image](https://user-images.githubusercontent.com/35910578/109346046-b37fdb00-7836-11eb-8f20-f5d446b39853.png)

* **What is the expected behavior?**
  * Layers can contain both `path` and `package` properties
  * `package` is of type 'object' rather than 'string'

* **Please tell us about your environment:**
  - Plugin version: v0.5.30
  - VSCode version: v1.53.2
  - Template type: serverless.yml (serverless framework)

* **Other information**
  * Potentially fix by changing `serverless-framework-schema\json\aws\layers.json`
  * First error:
    * Based on #114 it sounds like `layer.oneOf` should be `layer.anyOf`
  * Second:
    * Change `layer.package` from

  ```yml
  "package": {
    "type": "string",
    "properties": {
        "package": {
            "type": "any"
        },
        "artifact": {
            "type": "string",
            "description": "You can also specify a prebuilt archive to create your layer. When you do this, you do not need to specify the path element of your layer."
        }
    }
  }
  ```

  to 

  ```yml
  "package": {
    "$ref": "#/definitions/common:package-config"
  }
  ```
    * Possible issues with this:
      * `artifact.description`s don't match
      * `excludeDevDependencies` isn't a valid property for `layer.package`
