### ISSUE TITLE
"Unexpected property destinations" when setting failure destinations for kinesis streams

### ISSUE THREAD

**Issue by samskiter** [threadheap/serverless-ide-vscode#169]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behaviour?**
When using [serverless framework kinesis streams destinations](https://www.serverless.com/framework/docs/providers/aws/events/streams) Serverless IDE reports an unexpected property.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar.

Code (copied from the above documentation link): 

```yaml
functions:
  preprocess2:
    handler: handler.preprocess
    events:
      - stream:
          arn: arn:aws:kinesis:region:XXXXXX:stream/foo
          batchSize: 100
          maximumRetryAttempts: 10
          startingPosition: LATEST
          enabled: false
          destinations:
            onFailure:
              arn:
                Fn::GetAtt:
                  - MyQueue
                  - Arn
              type: sqs
```

The IDE:
![image](https://user-images.githubusercontent.com/1271643/179475313-3470e20a-3af9-4ec6-88bc-3885453cccc2.png)

* **What is the expected behaviour?**

As this is clearly a supported feature of serverless, I would not expect the serverless IDE to generate an error for this setup

* **What is the motivation / use case for changing the behavior?**

As above

* **Please tell us about your environment:**
  
  - Plugin version
    - Serverless IDE v0.5.34
  - VSCode version
    - Version: 1.69.0 (Universal)
  - Template type
    - YAML, serverless lambda
