### ISSUE TITLE
Value is not accepted when defining AWS::Cognito::IdentityPoolPrincipalTag 

### ISSUE THREAD

**Issue by adrian-mcmichael** [threadheap/serverless-ide-vscode#208]
When defining a resource of type [AWS::Cognito::IdentityPoolPrincipalTag](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-identitypoolprincipaltag.html) in my serverless.yml file I get the following validation error:

```
[Serverless IDE] Value is not accepted. Valid values: "AWS::ACMPCA::Certificate".
```

This is the block of code from my yml file:

```
    IdentityPrincipalTags:
      Type: AWS::Cognito::IdentityPoolPrincipalTag
      Properties:
        IdentityPoolId: { Ref: IdentityPool }
        IdentityProviderName: 
          Fn::GetAtt: [ "UserPool", "ProviderName" ]
        PrincipalTags:                 
          client_id: "aud"
          user_id: "sub"
        UseDefaults: false  
```

Running serverless itself it appears to have no issue with this creating this resource as I get this back in the logs:

```
  CREATE_COMPLETE - AWS::Cognito::IdentityPoolPrincipalTag - IdentityPrincipalTags
```

Are you able to add support for this resource type?
