### ISSUE TITLE
[Serverless IDE] Unexpected property kafka

### ISSUE THREAD

**Issue by EderLisboaa** [threadheap/serverless-ide-vscode#218]
Currently I receiving an error when using kafka as a event trigger on lambda: [Serverless IDE] Unexpected property kafka.

Has some example for how to configure a **Ignore Rules** to ignore this by now?

my serverless.yml:

```
functions:
  myFunction:
    handler: src/execute.handler
    events:
      - kafka:
          topic: myTopic
          bootstrapServers:
            - ${self:provider.environment.CONSUMER_BROKER_1}
            - ${self:provider.environment.CONSUMER_BROKER_2}
            - ${self:provider.environment.CONSUMER_BROKER_3}
          enabled: true
          batchSize: 50
          startingPosition: LATEST
```
