### ISSUE TITLE
Incorrect error E3002 on AWS::Location::Tracker

### ISSUE THREAD

**Issue by peragethemte** [threadheap/serverless-ide-vscode#224]
[Serverless IDE] E3002: Invalid Property Resources/EquipmentLocationTracker/Properties/EventBridgeEnabled

```
  EquipmentLocationTracker:  
    Type: AWS::Location::Tracker
    Properties:
      TrackerName: Equipments
      Description: Tracker for customer equipment
      EventBridgeEnabled: true
      PositionFiltering: DistanceBased
```
