### ISSUE TITLE
Support for MethodSettings in AWS::Serverless::API

### ISSUE THREAD

**Issue by DaveParr** [threadheap/serverless-ide-vscode#26]
Hi, just found this extension and it's saved me some time already.

I've run into a small inconsistency with the linter though:

```
....
MyAPIResource:
    Type: AWS::Serverless::Api
    Properties:
      StageName: MyStage
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          MetricsEnabled: True
          LoggingLevel: "INFO"
...
```

The above chunk is tagged by the linter as `[Serverless IDE] Incorrect type. Expected "object".`, however it passes a sam validate run and also can be packaged and deployed to enable those features which were implemented [in this release](https://github.com/awslabs/serverless-application-model/releases/tag/1.4.0). 

Other than that, thanks for the work :)

I'm using the extension as it is straight out the box. so using the cfn-lint option, with no customisation. Should that be the solution to this? I'm happy to modify the settings myself, but I'm pretty unclear on how to actually achieve that within the extension.
