### ISSUE TITLE
Adding support for !Condition and other tags

### ISSUE THREAD

**Issue by anhdle14** [threadheap/serverless-ide-vscode#41]
Just checking out the projects and it was very promising. But this is a critical issue i would imagined.

```json
{
	"resource": "****"
	"owner": "_generated_diagnostic_collection_name_#2",
	"severity": 8,
	"message": "[Serverless IDE] Unexpected property Condition",
	"startLineNumber": *,
	"startColumn": *,
	"endLineNumber": *,
	"endColumn": *
}
```

**Comment by pavelvlasov** [comment]
thanks for reporting @anhdle14 👍 are you using serverless framework or SAM/CloudFormation?
It would be great if you could also attach a code snippet to better understand the problem.

**Comment by anhdle14** [comment]
I think one of a reason is that you check the object with the [official documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-subnet.html). And in the official one, they did not acknowledge the use of Condition object, so it is not valid. 

```yaml
  PrivateSubnet1:
    Condition: 1AZCondition
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref PrivateSubnet1CIDR
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !Ref AvailabilityZones]
```
