### ISSUE TITLE
Unexpected Property (in serverless.yml)

### ISSUE THREAD

**Issue by ianbale** [threadheap/serverless-ide-vscode#46]
Hi,

I'm using [serverless-plugin-warmup](https://www.npmjs.com/package/serverless-plugin-warmup) plugin which means I am using some additional items in my serverless.ymp file:

```
  extend:
    handler: extend/handler.extend
    memorySize: 128
    timeout : 30
    events:
      - http:
          path: extend
          method: post
          private: true
    **warmup:
      enabled: false**
```

These are detected by lint and displayed as errors :

```
 [Serverless IDE] Unexpected property warmup
```

It seems trivial, but it results in the folder with these being shown in RED which takes precedence over the orange colour indicating that I have changes not yet committed to GIT. That is information that is useful to me, but is being obscured by these warnings.

I've disabled the Serverless IDE : Validate option for now which does get rid of it. But this does not seem like the ideal options as I would like the rest of the file to be validated.

I've spent some time trawling the docs here and those for lint, but I can't see what I need to configure to ignore these. Can anyone help please?
