### ISSUE TITLE
UpdateReplacePolicy errors

### ISSUE THREAD

**Issue by fragallia** [threadheap/serverless-ide-vscode#49]
When I put `UpdateReplacePolicy: Retain` directive into e.g. `AWS::Cognito::UserPool` resource definition, it shows error.

```
    UserPool:
      Type: "AWS::Cognito::UserPool"
      UpdateReplacePolicy: Retain
      Properties:
        ...
```
