### ISSUE TITLE
Add "Sid:" to serverless properties

### ISSUE THREAD

**Issue by mtompkins** [threadheap/serverless-ide-vscode#57]
Thanks for a great VSCode extension.

Please consider adding **Sid** to those known properties on serverless.

Example usage (YAML)

```
iamRoleStatements:
    - Sid: "AllowS3Operations"
      Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:PutObjectTagging"
```
