### ISSUE TITLE
apiKeys Name/Value Array Showing Validation Error

### ISSUE THREAD

**Issue by NJITman** [threadheap/serverless-ide-vscode#59]
serverless-ide-vscode V0.5.10 marks the following as **"[Serverless IDE] Incorrect type. Expected "string".",** even though it is correct syntax for serverless framework.

```
provider:
  apiKeys:
    - name: ${self:provider.stage}-key1
      value: keyvalue01longkeyvaluehere
      description: Key #1
    - name: ${self:provider.stage}-key2
      value: keyvalue01longkeyvaluehere
      description: Key #2

```
