### ISSUE TITLE
Incorrect Type. Expected "string".

### ISSUE THREAD

**Issue by counterbeing** [threadheap/serverless-ide-vscode#60]
I'm getting the red squiggly indicating a problem on  some `!Join` functions  where they are spread on multiple lines.

![image](https://user-images.githubusercontent.com/239798/71600547-45da0100-2b04-11ea-828d-fbbc9445ac6b.png)

My yaml is auto-formatted, and spreads lines like this over multiple. They are valid, as they run just fine.

Here's a larger snippet to make a possible test case out of: 
```yaml
    FrontEndAppCloudfront:
      Type: AWS::CloudFront::Distribution
      DependsOn:
        - FrontEndAppDeploymentBucket
      Properties:
        DistributionConfig:
          Comment: Cloudfront Distribution pointing to S3 bucket
          Origins:
            - DomainName: ${self:custom.baseName}.s3.amazonaws.com
              Id: S3Origin
              S3OriginConfig:
                OriginAccessIdentity:
                  !Join [
                    '',
                    [
                      'origin-access-identity/cloudfront/',
                      !Ref CloudfrontOriginAccessIdentity,
                    ],
                  ]
```
