### ISSUE TITLE
Value is not accepted. Valid values: "AWS::AccessAnalyzer::Analyzer"

### ISSUE THREAD

**Issue by counterbeing** [threadheap/serverless-ide-vscode#61]
I'm using a custom type for creating SSL certificates. This seems to be unsupported as of now.

```yaml
    WildcardCertificate:
      Type: Custom::IssuedCertificate
      DependsOn: CFNCustomProviderLambdaFunction
      Properties:
        CertificateArn: !Ref WildcardCertificateReques
```
