### ISSUE TITLE
Invalid caching Property

### ISSUE THREAD

**Issue by NJITman** [threadheap/serverless-ide-vscode#63]
The caching property for http under events is showing invalid,  See example below.  This property is added by the serverless-api-gateway-caching plugin.

```
  functionName:
    handler: functionName.handler
    name: ${opt:stage}-functionName
    description: ${opt:stage}-functionName
    events:
      - http:
          path: functionName/{param1}/{param2}
          method: get
          private: true
          request:
            parameters:
              paths:
                param1: true
                param2: true
              querystrings:
                param3: false
          caching:
            enabled: true
            cacheKeyParameters:
              - name: request.path.param1
              - name: request.path.param2
              - name: request.querystring.param3
```
Thanks - PGL
