### ISSUE TITLE
Invalid provider:logs property

### ISSUE THREAD

**Issue by kazbeel** [threadheap/serverless-ide-vscode#66]
When writing the following structure for API logs

```
logs:
    restApi:
      accessLogging: boolean
      executionLogging: boolean
      level: INFO | ERROR
      fullExecutionData: boolean
```

I get this error:

`[Serverless IDE] Incorrect type. Expected "boolean".`

Such structure is valid as you may see in [Serverless documentation](https://serverless.com/framework/docs/providers/aws/guide/serverless.yml) (search for "logs:"). Besides, it actually works.

The same error arises for `logs:websocket`:

```
logs:
    websocket:
        level: INFO | ERROR
```

Extra info:

Visual Studio Code: 1.41.1
OS: Windows 10
serverless-ide-vscode: 0.5.12
