### ISSUE TITLE
[Serverless IDE] Unexpected property existing

### ISSUE THREAD

**Issue by serverlesspolska** [threadheap/serverless-ide-vscode#67]
Hello,

I've got an error on correct property `existing` in function's definition -> events -> s3.

```
functions:
  users:
    handler: users.handler
    events:
      - s3:
          bucket: legacy-photos
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .jpg
          existing: true   <---- HERE PLUGIN COMPLAINS
```

Serverless Framework documentation can be found here
https://serverless.com/framework/docs/providers/aws/events/s3#using-existing-buckets

Could you please include this property?
