### ISSUE TITLE
Missing property "service" & "provider" when using lambda with AWS SQS  and Fn::GetAtt

### ISSUE THREAD

**Issue by Marcholio** [threadheap/serverless-ide-vscode#82]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Report a bug.

* **What is the current behavior?**
I have a lambda configured as follows:
```
 functionName:
    handler: src/handler.handler
    timeout: 10
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MySQS
              - Arn
          batchSize: 1
```

And the queue "MySQS" is defined in the same serverless file as the function. The IDE reports two errors:
- missing property "service"
- missing property "provider"

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar.
Minimum example:
```
service: my-service

provider:
  name: aws
  runtime: nodejs10.x

functions:
  # This works
  function1:
    handler: src/handler.handler
    events:
      - sqs:
          arn: "arn:aws:region:XXX:MyQueue"

  # This does not
  function2:
    handler: src/handler.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueueSQS
              - Arn

resources:
  Resources:
    MyQueueSQS:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: MyQueue
```

* **What is the expected behavior?**
There should not be an error.

* **What is the motivation / use case for changing the behavior?**
It's misleading since the Fn::GetAtt reference is working and according to the official [serverless documentation](https://www.serverless.com/framework/docs/providers/aws/events/sqs/).

* **Please tell us about your environment:**
  
  - Plugin version: 0.5.19
  - VSCode version: 1.44.2
  - Template type: serverless.yml

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Seems like the issue occurs only when using Fn::GetAtt, plain arn reference works fine.
