### ISSUE TITLE
Does not recognize "consumer" option in "stream"

### ISSUE THREAD

**Issue by kpeters-cbsi** [threadheap/serverless-ide-vscode#85]
**Note: what to raise a request for unknown/new or required field or resource, then raise a PR**.
#68 and #62
are good examples of updating a schema definition. It should not take longer that 15 minutes.

**What to prioritizer bugfix or feature?**
Hit that ❤️support button on the top of the screen.

**And don't forget to 🌟star the repo**

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

Bug

* **What is the current behavior?**

Serverless IDE does not recognize the "consumer" member of the "stream" object. 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar.

In serverless.yml:

```
functions:
  myFunc:
    handler: src/myfunc.handler
    events:
      - stream:
        type: kinesis
        consumer: true # <--- this gets flagged
        arn: arn:aws:kinesis:XXXXX:XXXXXX:stream/myStream
```

* **What is the expected behavior?**

The "consumer" member of the "stream" object should not be flagged as invalid

* **What is the motivation / use case for changing the behavior?**

https://www.serverless.com/framework/docs/providers/aws/events/streams/#dynamodb--kinesis-streams

Supported option to SLS stream configuration

* **Please tell us about your environment:**
  
  - Plugin version 0.5.21
  - VSCode version: 1.45.0
  - Template type: Unknown

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
