### ISSUE TITLE
[Serverless IDE] E3002: Invalid Property ForwardConfig

### ISSUE THREAD

**Issue by plinioh** [threadheap/serverless-ide-vscode#91]
**What to prioritizer bugfix or feature?**
Hit that ❤️support button on the top of the screen.

**And don't forget to 🌟star the repo**

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
This is a bug report

* **What is the current behavior?**
The linter is currently showing an incorrect error on a AWS::ElasticLoadBalancingV2::Listener configuration.
![image](https://user-images.githubusercontent.com/49917745/84195423-ed287000-aa74-11ea-8aff-6ecb369997c6.png)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via

Create a AWS::ElasticLoadBalancingV2::Listener with 2 default actions. A possible example is the configuration below:

```
  LoadBalancerHTTPSlistener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Sub 
            - "${LoadBalancerCertificateArn}"
            - LoadBalancerCertificateArn: {"Fn::ImportValue": !Sub "${ParentStack}-LoadBalancerCertificateArn"}
      DefaultActions:
        - Type: authenticate-cognito
          Order: 1
          AuthenticateCognitoConfig:
            UserPoolArn: !GetAtt UserPool.Arn
            UserPoolClientId: !Ref UserPoolClient
            UserPoolDomain: !Ref UserPoolDomain
            Scope: 'openid email'
            OnUnauthenticatedRequest: 'authenticate'
        - Type: forward
          Order: 2
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref TargetGroup
                Weight: 1
```

* **What is the expected behavior?**

The expected behaviour should be no linting errors, since i was able to upload and deploy the CloudFormation as is.

Also, this was already corrected in other plugins, as seen [here](https://github.com/aws-cloudformation/cfn-python-lint/issues/1251)

* **What is the motivation / use case for changing the behavior?**
N/A

* **Please tell us about your environment:**
  
  - Plugin version: 0.5.24
  - VSCode version: 1.40.2
  - Template type: 
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
```

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

If you wish, I can provide the Full Template in the thread.

I believe the issue with this plugin is similar to this: https://github.com/aws-cloudformation/cfn-python-lint/issues/1251
