### ISSUE TITLE
Bug: Serverless IDE Incorrectly Reports Required `Input` Parameter for Cloudwatch Event Target

### ISSUE THREAD

**Issue by BrutalSimplicity** [threadheap/serverless-ide-vscode#99]
The Serverless IDE is reporting an error when using the Cloudwatch Event type for a lambda function.

> [Serverless IDE] Missing property "input".

I don't believe this parameter is required.

VSCode Version: 1.47
Serverless IDE Version: 0.5.24

I have a serverless yml similar to the following:

```
service:
  name: example-service

provider:
  name: aws
  runtime: python3.8
  memorySize: 256

plugins:
  - serverless-python-requirements

functions:
  DeploymentStatus:
    name: some-service-${opt:stage}
    handler: handler.handler
    events:
      - cloudwatchEvent:
          event:
            source:
              - source1
              - source2

```
